innova_forum_multimodal_add_subject:
    path:  /forum/collectorama
    defaults: { _controller: InnovaForumMultimodalBundle:Forum:addSubject }

innova_forum_multimodal_add_contribution_file:
    path:  /forum/contribution/subject/{id}/add/file
    defaults: { _controller:InnovaForumMultimodalBundle:Contribution:addContributionFile}
    requirements:
        id:  \d+

innova_forum_multimodal_add_commentaire_text:
    path:  /forum/commentaire/add/text/{id}
    defaults: { _controller:InnovaForumMultimodalBundle:Contribution:AddCommentaireText}
    requirements:
        id:  \d+

innova_forum_multimodal_add_commentaire_file:
    path:  /forum/commentaire/add/file/{id}
    defaults: { _controller:InnovaForumMultimodalBundle:Contribution:AddCommentaireFile}
    requirements:
        id:  \d+

test:
    resource: "@InnovaForumMultimodalBundle/Controller/"
    type:       annotation
    prefix:     /

innova_forum_page_accueil:
    path:  /welcome
    defaults: { _controller: InnovaForumMultimodalBundle:Forum:welcome }

innova_sans_connexion:
    path:  /
    defaults: { _controller: InnovaForumMultimodalBundle:Forum:welcome }

innova_forum_multimodal_voir_contribution:
    path:  /forum/contribution/subject/{id}
    defaults: { _controller:InnovaForumMultimodalBundle:Contribution:showContribution}
    requirements:
        id:  \d+

innova_forum_multimodal_voir_commentaire:
    path:  /forum/commentaire/contribution/{id}
    defaults: { _controller:InnovaForumMultimodalBundle:Contribution:showCommentaire}
    requirements:
        id:  \d+

innova_forum_multimodal_delete_contribution:
    path:  /forum/contribution/delete/{id}
    defaults: { _controller:InnovaForumMultimodalBundle:Contribution:deleteContribution}
    requirements:
        id:  \d+

innova_forum_multimodal_update_contribution:
    path:  /forum/contribution/update/{id}
    defaults: { _controller:InnovaForumMultimodalBundle:Contribution:updateContribution}
    requirements:
        id:  \d+

innova_forum_multimodal_upload:
    pattern:  /forum/contribution/add/oral
    defaults: { _controller:InnovaForumMultimodalBundle:Ajax:upload}
    options:
        expose: true

innova_forum_multimodal_view_slideshow:
    path:  /forum/contribution/subject/{id}/slideshow
    defaults: { _controller:InnovaForumMultimodalBundle:Contribution:showSlideshow}
    requirements:
        id:  \d+

innova_forum_multimodal_download_slideshow:
    path:  /forum/contribution/subject/{id}/slideshow/download
    defaults: { _controller:InnovaForumMultimodalBundle:Contribution:downloadSlideshow}
    requirements:
        id:  \d+

innova_forum_multimodal_listen:
    pattern:  /forum/contribution/listen
    defaults: { _controller:InnovaForumMultimodalBundle:Ajax:listen}
    options:
        expose: true