innova_forum_multimodal_homepage:
    path:  /
    defaults: { _controller: InnovaForumMultimodalBundle:Forum:addSubject }

innova_forum_multimodal_add_contribution_text:
    path:  /forum/subject/{id}/contribution/add/text
    defaults: { _controller:InnovaForumMultimodalBundle:Contribution:addContribution}
    requirements:
        id:  \d+

innova_forum_multimodal_add_contribution_file:
    path:  /forum/subject/{id}/contribution/add/file
    defaults: { _controller:InnovaForumMultimodalBundle:Contribution:addContributionFile}
    requirements:
        id:  \d+

test:
    resource: "@InnovaForumMultimodalBundle/Controller/"
    type:       annotation
    prefix:     /

innova_forum_page_accueil:
    path:  /welcome
    defaults: { _controller: InnovaForumMultimodalBundle:Forum:welcome }

innova_sans_connexion:
    path:  /
    defaults: { _controller: InnovaForumMultimodalBundle:Forum:index }

innova_forum_multimodal_voir_contribution:
    path:  /forum/show/subject/{id}/contribution
    defaults: { _controller:InnovaForumMultimodalBundle:Contribution:showContribution}
    requirements:
        id:  \d+

innova_forum_multimodal_upload:
    pattern:  /forum/contribution/add/oral
    defaults: { _controller:InnovaForumMultimodalBundle:Ajax:upload}
    options:
        expose: true