<?php

namespace Innova\ForumMultimodalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * innovaSujetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class innovaSujetRepository extends EntityRepository
{
}
